# Generated by Django 3.2.10 on 2022-09-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myadmin', '0047_level_desig_temp1'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageInsp',
            fields=[
                ('message_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_sent', models.CharField(max_length=500, null=True)),
                ('message_reply', models.CharField(max_length=500, null=True)),
                ('message_by', models.CharField(max_length=15, null=True)),
                ('message_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('delete', models.BooleanField(default=False)),
                ('message_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig')),
            ],
        ),
    ]
