# Generated by Django 3.2 on 2022-07-01 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0043_auto_20220701_1648'),
        ('myadmin', '0015_divisonmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmastnew',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspects.empmast'),
        ),
        migrations.DeleteModel(
            name='empmast',
        ),
    ]
