# Generated by Django 3.2 on 2022-07-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0017_auto_20220701_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level_desig',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
