# Generated by Django 3.2 on 2022-07-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0018_alter_level_desig_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level_desig',
            old_name='id',
            new_name='designation_code',
        ),
    ]
