# Generated by Django 3.2 on 2022-07-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0019_rename_id_level_desig_designation_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMaster',
            fields=[
                ('code', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('admin', models.CharField(max_length=30)),
                ('admin_mobile', models.BigIntegerField(unique=True)),
                ('admin_phone', models.CharField(max_length=12, null=True)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(max_length=10)),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.locationmaster')),
                ('rly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.railwaylocationmaster')),
            ],
            options={
                'db_table': 'AdminMaster',
            },
        ),
        migrations.RemoveField(
            model_name='headquartermaster',
            name='headquarter_rly',
        ),
        migrations.RemoveField(
            model_name='headquartermaster',
            name='pincode',
        ),
        migrations.DeleteModel(
            name='divisonMaster',
        ),
        migrations.DeleteModel(
            name='headquarterMaster',
        ),
    ]
