# Generated by Django 3.2 on 2022-07-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0020_auto_20220702_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmaster',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
