# Generated by Django 3.2 on 2022-07-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0027_remove_hrms_emptype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HRMS',
        ),
    ]
