# Generated by Django 3.2 on 2022-07-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0028_delete_hrms'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRMS',
            fields=[
                ('ipas_employee_id', models.CharField(max_length=15)),
                ('hrms_employee_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('employee_first_name', models.CharField(max_length=150, null=True)),
                ('employee_middle_name', models.CharField(max_length=150, null=True)),
                ('employee_last_name', models.CharField(max_length=150, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('appointment_date', models.DateField(null=True)),
                ('superannuation_date', models.DateField(null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('community_sr', models.CharField(max_length=3, null=True)),
                ('service_status', models.CharField(max_length=50, null=True)),
                ('billunit', models.CharField(max_length=7, null=True)),
                ('railway_group', models.CharField(max_length=1, null=True)),
                ('current_zone', models.CharField(max_length=10, null=True)),
                ('current_unit_division', models.CharField(max_length=80, null=True)),
                ('current_place', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('sub_department', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=300, null=True)),
                ('paylevel', models.CharField(max_length=4, null=True)),
                ('official_mobile_no', models.CharField(max_length=10, null=True)),
                ('official_email_id', models.CharField(max_length=50, null=True)),
                ('txn_timestamp', models.DateTimeField(null=True)),
            ],
        ),
    ]
