# Generated by Django 3.2 on 2022-07-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0029_hrms'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrms',
            name='rltype',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
