# Generated by Django 3.2 on 2022-07-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0030_hrms_rltype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HRMS',
        ),
    ]
