# Generated by Django 3.2 on 2022-07-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0070_alter_myuser_email'),
        ('myadmin', '0034_alter_empmastnew_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='level_desig',
            name='empno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.empmast'),
        ),
        migrations.AddField(
            model_name='level_desig',
            name='status',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
