# Generated by Django 3.2 on 2022-07-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0035_auto_20220721_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level_desig',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='level_desig',
            name='level',
        ),
        migrations.RemoveField(
            model_name='level_desig',
            name='un_officer_id',
        ),
    ]
