# Generated by Django 3.2 on 2022-07-21 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0036_auto_20220721_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level_desig',
            old_name='pc7_level',
            new_name='pc7_levelmax',
        ),
        migrations.AddField(
            model_name='level_desig',
            name='pc7_levelmin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='level_desig',
            name='rly_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.railwaylocationmaster'),
        ),
    ]
