# Generated by Django 3.2 on 2022-07-21 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0039_runningroom_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningroom_master',
            name='created_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='runningroom_master',
            name='lastmodified_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='runningroom_master',
            name='stnshortcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.station_master'),
        ),
        migrations.AlterField(
            model_name='station_master',
            name='created_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='station_master',
            name='lastmodified_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='station_master',
            name='rly_id_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.railwaylocationmaster'),
        ),
        migrations.AlterField(
            model_name='stationcat_master',
            name='created_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stationcat_master',
            name='lastmodified_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
