# Generated by Django 3.2 on 2022-07-21 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0040_auto_20220721_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='inspectiontype_master',
            fields=[
                ('instypeid', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('shortcode', models.CharField(max_length=10, unique=True)),
                ('entity', models.CharField(max_length=10)),
                ('parent_id', models.CharField(max_length=10, unique=True)),
                ('statuschecklist', models.IntegerField(max_length=1)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('lastmodified_on', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='train_master',
            fields=[
                ('tnid', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('train_no', models.CharField(max_length=6, unique=True)),
                ('train_name', models.CharField(max_length=50)),
                ('tn_category', models.CharField(max_length=20, null=True)),
                ('stnsource_code', models.CharField(max_length=20, null=True)),
                ('stndest_code', models.CharField(max_length=20, null=True)),
                ('total_coach', models.IntegerField(max_length=2)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('lastmodified_on', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='traincat_master',
            fields=[
                ('tcatid', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('tn_category', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('lastmodified_on', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='section_master',
            fields=[
                ('secid', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('section_code', models.CharField(max_length=20, null=True)),
                ('secstart_code', models.CharField(max_length=20, null=True)),
                ('secend_code', models.CharField(max_length=20, null=True)),
                ('via', models.CharField(max_length=20, null=True)),
                ('startkm', models.IntegerField(max_length=5)),
                ('endkm', models.IntegerField(max_length=5)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('lastmodified_on', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('rly_id_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.railwaylocationmaster')),
            ],
        ),
    ]
