# Generated by Django 3.2 on 2022-07-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0041_inspectiontype_master_section_master_train_master_traincat_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='level_desig',
            name='d_level',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
