# Generated by Django 3.2 on 2022-08-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0044_auto_20220802_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railwaylocationmaster',
            name='location_description',
            field=models.CharField(max_length=100),
        ),
    ]
