# Generated by Django 3.2 on 2022-08-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0045_alter_railwaylocationmaster_location_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
