# Generated by Django 3.2 on 2022-08-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='choicetype_master',
        ),
        migrations.DeleteModel(
            name='dropdown_options',
        ),
        migrations.DeleteModel(
            name='radio_options',
        ),
    ]
