# Generated by Django 3.2 on 2022-08-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('einspect', '0002_auto_20220823_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='choicetype_master',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('input_type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dropdown_options',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('dmaster', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='radio_options',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rscore', models.IntegerField(max_length=1, null=True)),
                ('rlabel', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
