# Generated by Django 3.2 on 2022-08-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0004_questionare_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='einspection_details',
            fields=[
                ('einspno', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('instypeid', models.CharField(max_length=50, null=True)),
                ('inspection_officer_id', models.CharField(max_length=50, null=True)),
                ('inspected_on', models.DateTimeField(null=True)),
                ('inspection_title', models.CharField(max_length=200, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('inspection_note_no', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.IntegerField(max_length=1)),
                ('dept', models.CharField(max_length=20, null=True)),
                ('report_path', models.CharField(max_length=50, null=True)),
                ('rly_id_id', models.CharField(max_length=50, null=True)),
                ('startstn', models.CharField(max_length=50, null=True)),
                ('endstn', models.CharField(max_length=50, null=True)),
                ('entitydetails', models.CharField(max_length=30, null=True)),
                ('entityid', models.CharField(max_length=10)),
                ('rostetrdetail_id', models.CharField(max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(null=True)),
                ('lastmodified_on', models.DateTimeField(null=True)),
                ('delete_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
