# Generated by Django 3.2 on 2022-08-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0005_einspection_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='einspection_item_detail',
            fields=[
                ('eitemid', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.IntegerField(max_length=1, null=True)),
                ('value', models.CharField(max_length=50, null=True)),
                ('remarks', models.CharField(max_length=50, null=True)),
                ('target_date', models.DateTimeField(auto_now=True)),
                ('qtype', models.CharField(max_length=50, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('lastmodified_by', models.CharField(max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('lastmodified_on', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.BooleanField(default=False, null=True)),
                ('einspno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.einspection_details')),
                ('qid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='einspect.questionare_master')),
            ],
        ),
    ]
