# Generated by Django 3.2 on 2022-08-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0006_einspection_item_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='einsp_marked',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('eitemid', models.CharField(max_length=50, null=True)),
                ('marked_to', models.CharField(max_length=50, null=True)),
                ('marked_emp_id', models.CharField(max_length=50, null=True)),
                ('compliance', models.CharField(max_length=50, null=True)),
                ('compliance_recieved_on', models.DateTimeField(null=True)),
                ('status_flag', models.IntegerField(max_length=1, null=True)),
                ('revert', models.CharField(max_length=50, null=True)),
                ('reverted_on', models.DateTimeField(null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('lastmodified_on', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
