# Generated by Django 3.2 on 2022-07-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einspect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='einsp_marked',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('eitemid', models.CharField(max_length=50, null=True)),
                ('marked_to', models.CharField(max_length=50, null=True)),
                ('marked_emp_id', models.CharField(max_length=50, null=True)),
                ('compliance', models.CharField(max_length=50, null=True)),
                ('compliance_recieved_on', models.DateTimeField(null=True)),
                ('status_flag', models.IntegerField(max_length=1, null=True)),
                ('revert', models.CharField(max_length=50, null=True)),
                ('reverted_on', models.DateTimeField(null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('lastmodified_on', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='einspection_details',
            fields=[
                ('einspno', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('instypeid', models.CharField(max_length=50, null=True)),
                ('inspection_officer_id', models.CharField(max_length=50, null=True)),
                ('inspected_on', models.DateTimeField(null=True)),
                ('inspection_title', models.CharField(max_length=200, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('inspection_note_no', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.IntegerField(max_length=1)),
                ('dept', models.CharField(max_length=20, null=True)),
                ('report_path', models.CharField(max_length=50, null=True)),
                ('rly_id_id', models.CharField(max_length=50, null=True)),
                ('startstn', models.CharField(max_length=50, null=True)),
                ('endstn', models.CharField(max_length=50, null=True)),
                ('entitydetails', models.CharField(max_length=30, null=True)),
                ('entityid', models.CharField(max_length=10)),
                ('rostetrdetail_id', models.CharField(max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(null=True)),
                ('lastmodified_on', models.DateTimeField(null=True)),
                ('delete_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='einspection_item_detail',
            fields=[
                ('eitemid', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('einspno', models.CharField(max_length=50, null=True)),
                ('qid', models.CharField(max_length=50, null=True)),
                ('status', models.IntegerField(max_length=1)),
                ('einsdetailid', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=100)),
                ('target_date', models.DateTimeField()),
                ('qtype', models.CharField(max_length=10)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('lastmodified_on', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='questionare_master',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('instypeid_id', models.CharField(max_length=30)),
                ('activity', models.CharField(max_length=200)),
                ('choicetype', models.CharField(max_length=15, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('lastmodified_on', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
