# Generated by Django 3.2 on 2022-06-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0041_auto_20220629_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_details',
            name='item_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
