# Generated by Django 3.2 on 2022-07-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0043_auto_20220701_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_details',
            name='send_to',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
