# Generated by Django 3.2 on 2022-07-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0047_auto_20220705_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insp_mail_details',
            fields=[
                ('mail_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('body', models.CharField(max_length=500, null=True)),
                ('send_to', models.CharField(max_length=100, null=True)),
                ('send_desig', models.CharField(max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('area', models.CharField(max_length=10, null=True)),
                ('inspection_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.inspection_details')),
            ],
        ),
    ]
