# Generated by Django 3.2 on 2022-07-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0048_insp_mail_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event_activty',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('Railways_act', models.CharField(max_length=30, null=True)),
                ('Division_act', models.CharField(max_length=30, null=True)),
                ('location3_act', models.CharField(max_length=30, null=True)),
                ('date_to_act', models.DateField(null=True)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.events')),
            ],
        ),
    ]
