# Generated by Django 3.2 on 2022-07-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0051_auto_20220706_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='marked_officers',
            name='reply_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='marked_officers',
            name='status_flag',
            field=models.IntegerField(null=True),
        ),
    ]
