# Generated by Django 3.2 on 2022-07-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0052_auto_20220708_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection_details',
            name='status_flag',
            field=models.IntegerField(default=0),
        ),
    ]
