# Generated by Django 3.2 on 2022-07-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0053_alter_inspection_details_status_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_details',
            name='item_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
