# Generated by Django 3.2 on 2022-07-12 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0054_inspection_details_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officers_Remark',
            fields=[
                ('remark_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('rejected_on', models.DateTimeField(null=True)),
                ('reply_on', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('status_flag', models.IntegerField(default=0)),
                ('marked_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.marked_officers')),
            ],
        ),
    ]
