# Generated by Django 3.2 on 2022-07-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0055_officers_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_details',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
