# Generated by Django 3.2 on 2022-07-15 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0057_auto_20220715_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrigendum_Report',
            fields=[
                ('report_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('marked_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.marked_officers')),
            ],
        ),
    ]
