# Generated by Django 3.2 on 2022-07-18 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0032_hrms'),
        ('inspects', '0059_officers_remark_myuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empmast',
            old_name='parent',
            new_name='currentunitdivision',
        ),
        migrations.RenameField(
            model_name='empmast',
            old_name='decode_paycategory',
            new_name='empfname',
        ),
        migrations.RenameField(
            model_name='empmast',
            old_name='emp_inctype',
            new_name='emplname',
        ),
        migrations.RenameField(
            model_name='empmast',
            old_name='emp_status',
            new_name='empmname',
        ),
        migrations.RenameField(
            model_name='empmast',
            old_name='emptype',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='div_id',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='empname',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='idcard_no',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='inc_category',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='medicalcode',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='office',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='office_orderno',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='op_create',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='op_delete',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='op_read',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='op_update',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='parentshop',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='payband',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='payrate',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='rectt_category',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='scalecode',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='shop_section',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='shopno',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='ticket_no',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='tradecode',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='wau',
        ),
        migrations.AddField(
            model_name='empmast',
            name='currentzone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empmast',
            name='hrms_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.hrms'),
        ),
        migrations.AddField(
            model_name='empmast',
            name='railwaygroup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empmast',
            name='rl_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empmast',
            name='subdepartment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empmast',
            name='superannuation_date',
            field=models.DateField(null=True),
        ),
    ]
