# Generated by Django 3.2 on 2022-07-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0060_auto_20220718_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_details',
            name='insp_last',
            field=models.IntegerField(null=True),
        ),
    ]
