# Generated by Django 3.2 on 2022-07-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0061_inspection_details_insp_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='officers_remark',
            name='reply_received',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
