# Generated by Django 3.2 on 2022-07-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0062_officers_remark_reply_received'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empmast',
            old_name='empfname',
            new_name='empname',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='empmast',
            name='date_of_promotion',
        ),
        migrations.AlterField(
            model_name='inspection_details',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inspection_details',
            name='modified_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marked_officers',
            name='marked_emp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
