# Generated by Django 3.2 on 2022-07-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0063_auto_20220720_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='empmast',
        ),
    ]
