# Generated by Django 3.2 on 2022-07-20 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0034_alter_empmastnew_emp_id'),
        ('inspects', '0064_delete_empmast'),
    ]

    operations = [
        migrations.CreateModel(
            name='empmast',
            fields=[
                ('empno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=50, null=True)),
                ('empmname', models.CharField(max_length=50, null=True)),
                ('emplname', models.CharField(max_length=50, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('appointmentdate', models.DateField(null=True)),
                ('superannuation_date', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('contactno', models.CharField(blank=True, max_length=10, null=True)),
                ('railwaygroup', models.CharField(blank=True, max_length=50, null=True)),
                ('pc7_level', models.CharField(max_length=10, null=True)),
                ('billunit', models.CharField(max_length=50, null=True)),
                ('service_status', models.CharField(max_length=50, null=True)),
                ('desig_longdesc', models.CharField(max_length=50, null=True)),
                ('desig_id', models.CharField(max_length=50, null=True)),
                ('station_des', models.CharField(max_length=50, null=True)),
                ('dept_desc', models.CharField(max_length=50, null=True)),
                ('subdepartment', models.CharField(blank=True, max_length=50, null=True)),
                ('currentzone', models.CharField(blank=True, max_length=50, null=True)),
                ('currentunitdivision', models.CharField(blank=True, max_length=50, null=True)),
                ('rl_type', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_modified_on', models.DateField(blank=True, null=True)),
                ('hrms_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.hrms')),
                ('myuser_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rly_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empmast_rly_id', to='myadmin.railwaylocationmaster')),
            ],
        ),
    ]
