# Generated by Django 3.2 on 2022-07-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0065_empmast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HRMS',
        ),
    ]
