# Generated by Django 3.2 on 2022-07-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0066_delete_hrms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmast',
            name='currentunitdivision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
