# Generated by Django 3.2 on 2022-07-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0067_alter_empmast_currentunitdivision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmast',
            name='station_des',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
