# Generated by Django 3.2 on 2022-07-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0069_auto_20220720_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email address'),
        ),
    ]
