# Generated by Django 3.2 on 2022-07-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0070_alter_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='marked_officers_forward',
            name='reply_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='marked_officers_forward',
            name='status_flag',
            field=models.IntegerField(null=True),
        ),
    ]
