# Generated by Django 3.2 on 2022-07-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0071_auto_20220722_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.IntegerField(null=True)),
                ('menu', models.CharField(max_length=50, null=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('perent_id', models.IntegerField(null=True)),
                ('role', models.CharField(max_length=200, null=True)),
                ('icons', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='marked_officers',
            name='viewed_on',
            field=models.DateField(null=True),
        ),
    ]
