# Generated by Django 3.2 on 2022-07-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0074_auto_20220729_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.IntegerField(null=True)),
                ('menu', models.CharField(max_length=50, null=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('perent_id', models.IntegerField(null=True)),
                ('role', models.CharField(max_length=200, null=True)),
                ('icons', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='custom_menu2',
        ),
    ]
