# Generated by Django 3.2 on 2022-08-01 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0075_auto_20220729_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insp_multi_location',
            fields=[
                ('location_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=5, null=True)),
                ('d_flag', models.IntegerField(default=0)),
                ('inspection_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.inspection_details')),
            ],
        ),
    ]
