# Generated by Django 3.2 on 2022-08-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0076_insp_multi_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_details',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='inspection_details',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
