# Generated by Django 3.2 on 2022-08-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0080_alter_insp_mail_details_send_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_details',
            name='created_by',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='modified_by',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='marked_officers',
            name='created_by',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='marked_officers',
            name='modified_by',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
