# Generated by Django 3.2 on 2022-08-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0081_auto_20220806_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_details',
            name='status_flag',
            field=models.IntegerField(default=0),
        ),
    ]
