# Generated by Django 3.2 on 2022-08-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0082_alter_item_details_status_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insp_mail_details',
            name='send_to',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
