# Generated by Django 3.2 on 2022-08-10 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0044_auto_20220802_1509'),
        ('inspects', '0083_alter_insp_mail_details_send_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='officers_remark',
            name='marked_desig_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig'),
        ),
        migrations.AddField(
            model_name='officers_remark',
            name='marked_no_forward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.marked_officers_forward'),
        ),
    ]
