# Generated by Django 3.2 on 2022-08-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0084_auto_20220810_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_details',
            name='item_subtitle',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
